site_name: BentoDevelopment Docs
site_url: https://bentodevelopment.github.io/docs/
site_author: Joe Hosten
# Repository

repo_name: bentodevelopment/docs
repo_url: https://github.com/BentoDevelopment/docs/

nav:
  - Home: changelog.md
  - Blog: blog/index.md
  - BentoDevelopment:
      - products/index.md
  - Pronouns4j:
    - pronouns4j/index.md
    - pronouns4j/changelog.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  logo: assets/logo-v6.png
  favicon: assets/logo-v6.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  font:
    text: Lato
  features:
    - navigation.footer
    - search.suggest
    - navigation.instant

plugins:
  - search
  - blog:
      post_date_format: medium

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gNTPAsJRZt
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/BentoDevelopment
      name: Github

copyright: Copyright &copy; 2024 BentoDevelopment, Joseph Hosten