site_name: BentoDevelopment Docs
site_url: https://bentodevelopment.github.io/docs/
site_author: Joe Hosten
# Repository

repo_name: bentodevelopment/docs
repo_url: https://github.com/BentoDevelopment/docs/

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Pronouns4j:
    - pronouns4j/index.md
    - pronouns4j/changelog.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  logo: assets/logo-v6.png
  favicon: assets/logo-v6.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  font:
    text: Lato
  features:
    - navigation.footer
    - search.suggest
    - navigation.instant
    - content.code.copy
    - content.code.select
    - content.code.annotate

plugins:
  - search
  - blog:
      post_date_format: medium

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  status:
    new: Recently added
    updated: Recently updated
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gNTPAsJRZt
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/BentoDevelopment
      name: Github

copyright: Copyright &copy; 2024 BentoDevelopment, Joseph Hosten